name: Validate generated YARA

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download Velociraptor binaries
      run: |
          VERSION="$(
            curl -s https://api.github.com/repos/Velocidex/velociraptor/releases/latest \
            | grep '"tag_name":' \
            | cut -d '"' -f 4 \
            | sed 's/^v//'
          )"
          LINUX="$(
            curl -s https://api.github.com/repos/Velocidex/velociraptor/releases/tags/v$VERSION \
            | grep browser_download_url | cut -d '"' -f 4 | grep linux-amd64-musl
          )"
          WINDOWS="$(
            curl -s https://api.github.com/repos/Velocidex/velociraptor/releases/tags/v$VERSION \
            | grep browser_download_url | cut -d '"' -f 4 | grep 'windows-amd64\.exe'
          )"
          curl -L "$LINUX" -o ./velociraptor
          curl -L "$WINDOWS" -o ./velociraptor.exe
          chmod +x ./velociraptor
          ./velociraptor version

    - name: Validate generated YARA bundles
      run: bash ./scripts/validate_yara_with_velociraptor.sh ./velociraptor ./velociraptor.exe
